### ISSUE TITLE
ArgumentError on line 150 of autoprefixer-rails-7.1.4/lib/autoprefixer-rails/processor.rb: invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by jantoine1** [ai/autoprefixer-rails#125]
I'm running into the following error when running 'bundle exec compass watch' on a project.
```
>>> Compass is watching for changes. Press Ctrl-C to Stop.
    write css/styles.css
ArgumentError on line ["150"] of /usr/local/rvm/gems/ruby-2.4.2/gems/autoprefixer-rails-7.1.4/lib/autoprefixer-rails/processor.rb: invalid byte sequence in US-ASCII
```

Output with --trace
```
>>> Compass is watching for changes. Press Ctrl-C to Stop.
    write css/styles.css
ArgumentError on line ["150"] of /usr/local/rvm/gems/ruby-2.4.2/gems/autoprefixer-rails-7.1.4/lib/autoprefixer-rails/processor.rb: invalid byte sequence in US-ASCII
  /usr/local/rvm/gems/ruby-2.4.2/gems/autoprefixer-rails-7.1.4/lib/autoprefixer-rails/processor.rb:150:in `read_js'
  /usr/local/rvm/gems/ruby-2.4.2/gems/autoprefixer-rails-7.1.4/lib/autoprefixer-rails/processor.rb:228:in `build_js'
  /usr/local/rvm/gems/ruby-2.4.2/gems/autoprefixer-rails-7.1.4/lib/autoprefixer-rails/processor.rb:141:in `runtime'
  /usr/local/rvm/gems/ruby-2.4.2/gems/autoprefixer-rails-7.1.4/lib/autoprefixer-rails/processor.rb:36:in `process'
  /usr/local/rvm/gems/ruby-2.4.2/gems/autoprefixer-rails-7.1.4/lib/autoprefixer-rails.rb:13:in `process'
  /var/www/web/themes/dakota_theme/config.rb:42:in `block in get_binding'
  /usr/local/rvm/gems/ruby-2.4.2/gems/sass-3.4.25/lib/sass/callbacks.rb:61:in `block in run_stylesheet_saved'
  /usr/local/rvm/gems/ruby-2.4.2/gems/sass-3.4.25/lib/sass/callbacks.rb:61:in `each'
  /usr/local/rvm/gems/ruby-2.4.2/gems/sass-3.4.25/lib/sass/callbacks.rb:61:in `run_stylesheet_saved'
  /usr/local/rvm/gems/ruby-2.4.2/gems/compass-core-1.0.3/lib/compass/configuration/inheritance.rb:167:in `run_stylesheet_saved'
  /usr/local/rvm/gems/ruby-2.4.2/gems/compass-core-1.0.3/lib/compass/configuration/inheritance.rb:169:in `run_stylesheet_saved'
  /usr/local/rvm/gems/ruby-2.4.2/gems/compass-1.0.3/lib/compass/sass_compiler.rb:93:in `when_updated_stylesheet'
  /usr/local/rvm/gems/ruby-2.4.2/gems/compass-1.0.3/lib/compass/sass_compiler.rb:35:in `block (2 levels) in initialize'
  /usr/local/rvm/gems/ruby-2.4.2/gems/sass-3.4.25/lib/sass/callbacks.rb:61:in `block in run_updated_stylesheet'
  /usr/local/rvm/gems/ruby-2.4.2/gems/sass-3.4.25/lib/sass/callbacks.rb:61:in `each'
  /usr/local/rvm/gems/ruby-2.4.2/gems/sass-3.4.25/lib/sass/callbacks.rb:61:in `run_updated_stylesheet'
  /usr/local/rvm/gems/ruby-2.4.2/gems/sass-3.4.25/lib/sass/plugin/compiler.rb:510:in `update_stylesheet'
  /usr/local/rvm/gems/ruby-2.4.2/gems/sass-3.4.25/lib/sass/plugin/compiler.rb:215:in `block in update_stylesheets'
  /usr/local/rvm/gems/ruby-2.4.2/gems/sass-3.4.25/lib/sass/plugin/compiler.rb:209:in `each'
  /usr/local/rvm/gems/ruby-2.4.2/gems/sass-3.4.25/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
  /usr/local/rvm/gems/ruby-2.4.2/gems/sass-3.4.25/lib/sass/plugin/compiler.rb:294:in `watch'
  /usr/local/rvm/gems/ruby-2.4.2/gems/compass-1.0.3/lib/compass/sass_compiler.rb:46:in `watch!'
  /usr/local/rvm/gems/ruby-2.4.2/gems/compass-1.0.3/lib/compass/commands/watch_project.rb:41:in `perform'
  /usr/local/rvm/gems/ruby-2.4.2/gems/compass-1.0.3/lib/compass/commands/base.rb:18:in `execute'
  /usr/local/rvm/gems/ruby-2.4.2/gems/compass-1.0.3/lib/compass/commands/project_base.rb:19:in `execute'
  /usr/local/rvm/gems/ruby-2.4.2/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /usr/local/rvm/gems/ruby-2.4.2/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /usr/local/rvm/gems/ruby-2.4.2/gems/compass-1.0.3/bin/compass:30:in `block in <top (required)>'
  /usr/local/rvm/gems/ruby-2.4.2/gems/compass-1.0.3/bin/compass:44:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.4.2/bin/compass:23:in `load'
  /usr/local/rvm/gems/ruby-2.4.2/bin/compass:23:in `<main>'
  /usr/local/rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
  /usr/local/rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

Debian Jessie
`Linux c44211328b48 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 GNU/Linux`

Ruby is installed using RVM:
`rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]`

Ruby
`ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]`

Bundler
`Bundler version 1.15.4`

Let me know if I can provide any additional information.

**Comment by ai** [comment]
Do you use Autoprefixer for Compass? Can you show your config?

**Comment by ai** [comment]
Also, can you show output pf this terminal commands:

```sh
echo $LANG
echo $LANGUAGE
echo $LC_ALL
```

**Comment by jantoine1** [comment]
I'm checking w/ my front end developer on the first question, 'Do you use Autoprefixer for Compass?'

Contetns of config.rb
```
require 'compass/import-once/activate'
# Require any additional compass plugins here.

# Require other plugins / gems
require 'sass-globbing'

# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "css"
sass_dir = "sass"
images_dir = "images"
javascripts_dir = "javascripts"

sourcemap = true

# You can select your preferred output style here (can be overridden via the command line):
# output_style = :expanded or :nested or :compact or :compressed

# To enable relative paths to assets via compass helper functions. Uncomment:
# relative_assets = true

# To disable debugging comments that display the original location of your selectors. Uncomment:
# line_comments = false


# If you prefer the indented syntax, you might want to regenerate this
# project again passing --syntax sass, or you can uncomment this:
# preferred_syntax = :sass
# and then run:
# sass-convert -R --from scss --to sass sass scss && rm -rf sass && mv scss sass


# Autoprefixer hack
# For details, see: https://github.com/ai/autoprefixer-rails
require 'autoprefixer-rails'

on_stylesheet_saved do |file|
  css = File.read(file)
  map = file + '.map'

  if File.exists? map
    result = AutoprefixerRails.process(css,
      from: file,
      to:   file,
      map:  { prev: File.read(map), inline: false })
    File.open(file, 'w') { |io| io << result.css }
    File.open(map,  'w') { |io| io << result.map }
  else
    File.open(file, 'w') { |io| io << AutoprefixerRails.process(css) }
  end
end
```

echo $LANG
``

echo $LANGUAGE
``

echo $LC_ALL
``

**Comment by ai** [comment]
So all these 3 variables is empty/

**Comment by ai** [comment]
Try to write this in terminal and then run compass:

```sh
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by jantoine1** [comment]
Same error... would you like trace output?

**Comment by ai** [comment]
Nope. I will think about this issue on Monday.

**Comment by ai** [comment]
The main problem is that your Ruby uses wrong encoding. It should use UTF-8.

Try to google `ruby "invalid byte sequence in US-ASCII"` and try the method to change default encoding.

**Comment by ai** [comment]
Sorry, I didn't find solution. Same code works with me.

Try JS version of Autoprefixer with Gulp/webpack. Anyway it will be much faster.

**Comment by ai** [comment]
No report since 2017, since it was fixed
