### ISSUE TITLE
Autoprefixer doesn’t support Node v4.2.6. Update it.

### ISSUE THREAD

**Issue by xinlangzi** [ai/autoprefixer-rails#144]
```
ubuntu@:~$ yarn -v
1.9.4
ubuntu@:~$ node -v
v8.11.4
```

```
01 ~/.rvm/bin/rvm 2.5.1 do bundle exec rake assets:precompile
01 yarn install v1.9.4
01 warning package.json: No license field
01 warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution incon…
01 warning No license field
01 [1/4] Resolving packages...
01 [2/4] Fetching packages...
01 info fsevents@1.2.4: The platform "linux" is incompatible with this module.
01 info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
01 [3/4] Linking dependencies...
01 warning "@rails/webpacker > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
01 warning " > vue-loader@14.2.2" has unmet peer dependency "css-loader@*".
01 warning " > webpack-dev-server@2.11.2" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
01 warning "webpack-dev-server > webpack-dev-middleware@1.12.2" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
01 [4/4] Building fresh packages...
01 Done in 9.16s.
01 rake aborted!
01 Autoprefixer doesn’t support Node v4.2.6. Update it.
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/processor.rb:163:in `runtime'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/processor.rb:37:in `process'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/sprockets.rb:20:in `run'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/sprockets.rb:14:in `call'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:134:in `block in find'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `each'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `find'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/airbrake-7.3.5/lib/airbrake/rake.rb:17:in `execute'
01 /var/www/rails_app/shared/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
01 /home/ubuntu/.rvm/gems/ruby-2.5.1@global/gems/bundler-1.16.3/exe/bundle:30:in `block in <top (required)>'
01 /home/ubuntu/.rvm/gems/ruby-2.5.1@global/gems/bundler-1.16.3/exe/bundle:22:in `<top (required)>'
01 /home/ubuntu/.rvm/gems/ruby-2.5.1@global/bin/bundle:23:in `load'
01 /home/ubuntu/.rvm/gems/ruby-2.5.1@global/bin/bundle:23:in `<main>'
01 /home/ubuntu/.rvm/gems/ruby-2.5.1@global/bin/ruby_executable_hooks:15:in `eval'
01 /home/ubuntu/.rvm/gems/ruby-2.5.1@global/bin/ruby_executable_hooks:15:in `<main>'
01 Tasks: TOP => assets:precompile
01 (See full trace by running task with --trace)
```

**Comment by ai** [comment]
Try `nodejs -v`

**Comment by xinlangzi** [comment]
```
ubuntu@:~$ nodejs -v
v4.2.6
```

What should I do next step? 

My local macosx does not have nodejs, it only works when type node -v.

**Comment by ai** [comment]
You have 2 Node.js runtimes. One from deb package `nodejs`, second (I think) from `nvm`. ExecJS uses `nodejs` by default.

Remove `nodejs` deb package from Ubuntu

**Comment by Chrisgo-75** [comment]
Thank you. Spent 3 hrs on this and started thinking that this might be related to Ubuntu having its own package of nodejs installed ... vs I re-installed Rails Bootstrap gem multiple times, tried MANY various edits on the Rails side and NVM to no avail.

"Remove nodejs deb package from Ubuntu" fixed the issue that Rails was outputting.

**Comment by mainangethe** [comment]
> I just had the same problem but it was fixed after I update nodejs as it said:
> 
> (ubuntu)
> 
> ```
> $ curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
> $ sudo apt-get install -y nodejs
> ```

This was the only output that helped me resolve this issue
