### ISSUE TITLE
Node.js (V8) runtime does not work

### ISSUE THREAD

**Issue by betelgeuse** [ai/autoprefixer-rails#49]
With the Node.js runtime to ExecJS I get:

```
  1) layouts/application.html.haml should use configured title
     Failure/Error: render :template => 'layouts/application', :formats => [:html]
     ActionView::Template::Error:
       TypeError: Cannot read property 'process' of undefined
         (in /Users/betelgeuse/experq/backend/app/assets/stylesheets/application.css.scss)
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/execjs-1.2.13/lib/execjs/external_runtime.rb:67:in `extract_result'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/execjs-1.2.13/lib/execjs/external_runtime.rb:27:in `block in exec'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/execjs-1.2.13/lib/execjs/external_runtime.rb:40:in `compile_to_tempfile'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/execjs-1.2.13/lib/execjs/external_runtime.rb:26:in `exec'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/execjs-1.2.13/lib/execjs/external_runtime.rb:18:in `eval'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/execjs-1.2.13/lib/execjs/external_runtime.rb:32:in `call'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/autoprefixer-rails-5.0.0/lib/autoprefixer-rails/processor.rb:21:in `process'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/autoprefixer-rails-5.0.0/lib/autoprefixer-rails/sprockets.rb:15:in `process'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/autoprefixer-rails-5.0.0/lib/autoprefixer-rails/sprockets.rb:21:in `block in install'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/processor.rb:29:in `call'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/processor.rb:29:in `evaluate'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/context.rb:197:in `block in evaluate'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `each'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `evaluate'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:12:in `initialize'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `new'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `block in build_asset'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/base.rb:395:in `circular_call_protection'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/base.rb:373:in `build_asset'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/bundled_asset.rb:16:in `initialize'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `new'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `build_asset'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.12.3/lib/sprockets/base.rb:295:in `[]'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-rails-2.2.2/lib/sprockets/rails/helper.rb:123:in `asset_digest_path'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-rails-2.2.2/lib/sprockets/rails/helper.rb:76:in `compute_asset_path'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/actionpack-4.0.13/lib/action_view/helpers/asset_url_helper.rb:132:in `asset_path'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-rails-2.2.2/lib/sprockets/rails/helper.rb:91:in `asset_path'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/actionpack-4.0.13/lib/action_view/helpers/asset_url_helper.rb:256:in `stylesheet_path'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/actionpack-4.0.13/lib/action_view/helpers/asset_tag_helper.rb:97:in `block in stylesheet_link_tag'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/actionpack-4.0.13/lib/action_view/helpers/asset_tag_helper.rb:93:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/actionpack-4.0.13/lib/action_view/helpers/asset_tag_helper.rb:93:in `stylesheet_link_tag'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-rails-2.2.2/lib/sprockets/rails/helper.rb:170:in `stylesheet_link_tag'
     # ./app/views/layouts/application.html.haml:14:in `_app_views_layouts_application_html_haml___342424346557164092_70101402364540'
```

The runtime is

```
(byebug) p ExecJS.runtime
#<ExecJS::ExternalRuntime:0x007fe8ffc5f040 @name="Node.js (V8)", @command=["nodejs", "node"], @runner_path="/Users/betelgeuse/.rvm/gems/ruby-2.0.0-p598/gems/execjs-1.2.13/lib/execjs/support/node_runner.js", @test_args=nil, @test_match=nil, @encoding="UTF-8", @binary="node">
```

I checked with execjs-2.2.2 and it made no difference. I see two ways to approach this. Either fix whatever node.js does not like or then implement a check for ExecJS.runtime and give a better error message.

```
$ node --version
v0.10.33
```

**Comment by ai** [comment]
Update to 5.0.0.1. This bug was already fixed there.
