### ISSUE TITLE
browserslist entry with locale doesn't work

### ISSUE THREAD

**Issue by mixtur** [ai/autoprefixer-rails#72]
Basically with this browserslist
```
last 1 version
> 0.5%
Safari >= 5
iOS >= 6
```
everything works fine.
And with this

```
last 1 version
> 0.5% in US
Safari >= 5
iOS >= 6
```

`rake autoprefixer:info` fails with following message

```
rake aborted!
ExecJS::ProgramError: Error: Cannot find module 'caniuse-db/region-usage-json/US'
s ((execjs):1:796)
(execjs):1:953
Function.browserslist.queries.countryStatistics.select ((execjs):6608:28)
(execjs):6409:38
Array.forEach (native)
browserslist ((execjs):6395:16)
Browsers.parse ((execjs):680:14)
new Browsers ((execjs):675:28)
loadPrefixes ((execjs):601:18)
Function.plugin.info ((execjs):619:32)
/home/username/.rvm/gems/ruby-2.2.3@project_name/gems/execjs-2.6.0/lib/execjs/external_runtime.rb:39:in `exec'
/home/username/.rvm/gems/ruby-2.2.3@project_name/gems/execjs-2.6.0/lib/execjs/external_runtime.rb:21:in `eval'
/home/username/.rvm/gems/ruby-2.2.3@project_name/gems/autoprefixer-rails-6.0.3/lib/autoprefixer-rails/processor.rb:35:in `info'
/home/username/.rvm/gems/ruby-2.2.3@project_name/gems/autoprefixer-rails-6.0.3/lib/rake/autoprefixer_tasks.rb:23:in `block (2 levels) in define'
Tasks: TOP => autoprefixer:info
(See full trace by running task with --trace)
```

**Comment by ai** [comment]
Hm, I am thinking that I will bring you bad news ;).

Because of ExecJS limitations, Autoprefixer Rails has no country statistics support. Maybe I can spend a month a refactor Autoprefixer to add some hooks in Autoprefixer Rails, but Rails Assets Pipeline dies to do this work.

You should migrate to webpack/Gulp, it is much better way.

**Comment by ai** [comment]
I update a docs.
